// generated by znkr.io/diff/internal/cmd/specializemyers
// DO NOT EDIT

package impl

import (
	"math"

	"znkr.io/diff/internal/pool"
	"znkr.io/diff/internal/rvecs"
)

type myersInt struct {
	x, y []int

	vf, vb []int
	v0     int

	costLimit int

	xidx, yidx []int

	rx, ry rvecs.Vec
}

func (m *myersInt) init(x, y []int) (smin, smax, tmin, tmax int) {
	smin, tmin = 0, 0
	smax, tmax = len(x), len(y)

	for smin < smax && tmin < tmax && x[smin] == y[tmin] {
		smin++
		tmin++
	}

	for smax > smin && tmax > tmin && x[smax-1] == y[tmax-1] {
		smax--
		tmax--
	}

	N, M := smax-smin, tmax-tmin
	diagonals := N + M

	vlen := diagonals + 3
	buf := pool.Ints.Get(2 * vlen)

	m.x = x
	m.y = y
	m.vf = buf[:vlen]
	m.vb = buf[vlen:]
	m.v0 = M + 1

	costLimit := 1
	for i := diagonals; i != 0; i >>= 2 {
		costLimit <<= 1
	}
	m.costLimit = max(minCostLimit, costLimit)

	if m.rx.Len() == 0 || m.ry.Len() == 0 {
		m.rx, m.ry = rvecs.Make(len(x), len(y))
	}
	return
}

func (m *myersInt) release() {

	pool.Ints.Put(m.vf[:cap(m.vf)])
}

func (m *myersInt) compare(smin, smax, tmin, tmax int, optimal bool) {
	if smin == smax {

		if m.yidx == nil {
			m.ry.SetRange(tmin, tmax)
		} else {
			m.ry.SetSorted(m.yidx[tmin:tmax])
		}
	} else if tmin == tmax {

		if m.xidx == nil {
			m.rx.SetRange(smin, smax)
		} else {
			m.rx.SetSorted(m.xidx[smin:smax])
		}
	} else {

		s0, s1, t0, t1, opt0, opt1 := m.split(smin, smax, tmin, tmax, optimal)

		m.compare(smin, s0, tmin, t0, opt0)
		m.compare(s1, smax, t1, tmax, opt1)
	}
}

func (m *myersInt) split(smin, smax, tmin, tmax int, optimal bool) (s0, s1, t0, t1 int, opt0, opt1 bool) {
	N, M := smax-smin, tmax-tmin
	vf, vb := m.vf, m.vb
	v0 := m.v0

	kmin, kmax := smin-tmax, smax-tmin

	fmid, bmid := smin-tmin, smax-tmax
	fmin, fmax := fmid, fmid
	bmin, bmax := bmid, bmid

	odd := (N-M)%2 != 0

	vf[v0+fmid] = smin
	vb[v0+bmid] = smax

	for d := 1; ; d++ {

		if fmin > kmin {
			fmin--
			vf[v0+fmin-1] = math.MinInt
		} else {
			fmin++
		}
		if fmax < kmax {
			fmax++
			vf[v0+fmax+1] = math.MinInt
		} else {
			fmax--
		}
		fs0, fs1, ft0, ft1, flongest, found := m.forward(fmin, fmax, bmin, bmax, smax, tmax, odd)
		if found {
			return fs0, fs1, ft0, ft1, true, true
		}

		if bmin > kmin {
			bmin--
			vb[v0+bmin-1] = math.MaxInt
		} else {
			bmin++
		}
		if bmax < kmax {
			bmax++
			vb[v0+bmax+1] = math.MaxInt
		} else {
			bmax--
		}
		bs0, bs1, bt0, bt1, blongest, found := m.backward(bmin, bmax, fmin, fmax, smin, tmin, !odd)
		if found {
			return bs0, bs1, bt0, bt1, true, true
		}
		longestDiag := max(flongest, blongest)

		if optimal {
			continue
		}

		if longestDiag >= goodDiagMinLen && d >= goodDiagCostLimit {
			best := struct {
				v              int
				s0, s1, t0, t1 int
				opt0, opt1     bool
			}{}

			for k := fmin; k <= fmax; k += 2 {
				k0 := k + v0
				s := vf[k0]
				t := s - k
				v := (s - smin) + (t - tmin) - max(fmid-d, d-fmid)
				if s < smin || smax <= s || t < tmin || tmax <= t {
					continue
				}
				if v <= goodDiagMagic*d || v < best.v {
					continue
				}

				var pk int
				if vf[k0-1] < vf[k0+1] {
					pk = k + 1
				} else {
					pk = k - 1
				}
				ps := vf[pk+v0]
				pt := ps - pk
				diag := min(s-ps, t-pt)
				if diag >= goodDiagMinLen {
					best.v = v
					best.s0 = s - diag
					best.s1 = s
					best.t0 = t - diag
					best.t1 = t
					best.opt0 = true
					best.opt1 = false
				}
			}

			for k := bmin; k <= bmax; k += 2 {
				k0 := k + v0
				s := vb[k0]
				t := s - k
				if s < smin || smax <= s || t < tmin || tmax <= t {
					continue
				}
				v := (smax - s) + (tmax - t) - max(bmid-d, d-bmid)
				if v <= goodDiagMagic*d || v < best.v {
					continue
				}

				var pk int
				if vb[k0-1] < vb[k0+1] {
					pk = k - 1
				} else {
					pk = k + 1
				}
				ps := vb[pk+v0]
				pt := ps - pk
				diag := min(ps-s, pt-t)
				if diag >= goodDiagMinLen {
					best.v = v
					best.s0 = s
					best.s1 = s + diag
					best.t0 = t
					best.t1 = t + diag
					best.opt0 = false
					best.opt1 = true
				}
			}
			if best.v > 0 {
				return best.s0, best.s1, best.t0, best.t1, best.opt0, best.opt1
			}
		}

		if d >= m.costLimit {

			fbest, fbestk := math.MinInt, math.MinInt
			for k := fmin; k <= fmax; k += 2 {
				k0 := k + v0
				s := vf[k0]
				t := s - k
				if smin <= s && s < smax && tmin <= t && t < tmax && fbest < s+t {
					fbest = s + t
					fbestk = k
				}
			}

			bbest, bbestk := math.MaxInt, math.MaxInt
			for k := bmin; k <= bmax; k += 2 {
				k0 := k + v0
				s := vb[k0]
				t := s - k
				if smin <= s && s < smax && tmin <= t && t < tmax && s+t < bbest {
					bbest = s + t
					bbestk = k
				}
			}

			if fbest != math.MinInt && (smax+tmax)-bbest < fbest-(smin+tmin) {
				k := fbestk
				k0 := k + v0
				s := vf[k0]
				t := s - k

				var pk int
				if vf[k0-1] < vf[k0+1] {
					pk = k + 1
				} else {
					pk = k - 1
				}
				ps := vf[pk+v0]
				pt := ps - pk
				diag := min(s-ps, t-pt)
				s0, t0 := s-diag, t-diag
				return s0, s, t0, t, true, false
			} else if bbest != math.MaxInt {
				k := bbestk
				k0 := k + v0
				s := vb[k0]
				t := s - k

				var pk int
				if vb[k0-1] < vb[k0+1] {
					pk = k - 1
				} else {
					pk = k + 1
				}
				ps := vb[pk+v0]
				pt := ps - pk
				diag := min(ps-s, pt-t)
				s0, t0 := s+diag, t+diag
				return s, s0, t, t0, false, true
			} else {
				panic("no best path found")
			}
		}
	}
}

func (m *myersInt) forward(fmin, fmax, bmin, bmax, smax, tmax int, check bool) (s0, s1, t0, t1, longest int, found bool) {
	x, y := m.x[:smax], m.y[:tmax]

	lo, hi := m.v0+fmin-1, m.v0+fmax+2
	wf := m.vf[lo:hi]
	wb := m.vb[lo:hi][:len(wf)]

	for w := 1; w < len(wf)-1; w += 2 {
		k := fmin - 1 + w

		s := max(wf[w-1]+1, wf[w+1])
		t := s - k

		s0, t0 := s, t
		for uint(s) < uint(len(x)) && uint(t) < uint(len(y)) && x[s] == y[t] {
			s++
			t++
		}

		longest = max(longest, s-s0)

		wf[w] = s

		if check && bmin <= k && k <= bmax && s >= wb[w] {
			return s0, s, t0, t, longest, true
		}
	}
	return 0, 0, 0, 0, longest, false
}

func (m *myersInt) backward(bmin, bmax, fmin, fmax, smin, tmin int, check bool) (s0, s1, t0, t1, longest int, found bool) {
	xb, yb := m.x[smin:], m.y[tmin:]

	lo, hi := m.v0+bmin-1, m.v0+bmax+2
	wb := m.vb[lo:hi]
	wf := m.vf[lo:hi][:len(wb)]
	for w := 1; w < len(wb)-1; w += 2 {
		k := bmin - 1 + w
		s := min(wb[w-1], wb[w+1]-1)
		t := s - k

		s0, t0 := s, t
		i, j := s-smin, t-tmin
		for uint(i-1) < uint(len(xb)) && uint(j-1) < uint(len(yb)) && xb[i-1] == yb[j-1] {
			i--
			j--
		}
		s, t = i+smin, j+tmin

		longest = max(longest, s0-s)

		wb[w] = s

		if check && fmin <= k && k <= fmax && s <= wf[w] {
			return s, s0, t, t0, longest, true
		}
	}
	return 0, 0, 0, 0, longest, false
}
